openapi: 3.0.1
info:
  title: Azure OpenAI API version 2024-06-01
  description: APIs for fine-tuning and managing deployments of OpenAI models.
  version: '2024-06-01'
servers:
- url: /
paths:
  /models:
    get:
      tags:
      - 'Models:'
      summary: "Gets a list of all models that are accessible by the Azure OpenAI\
        \ resource.\r\nThese include base models as well as all successfully completed\
        \ fine-tuned models owned by the Azure OpenAI resource."
      operationId: Models_List
      parameters:
      - name: api-version
        in: query
        description: The requested API version.
        required: true
        style: form
        explode: true
        schema:
          type: string
          x-ms-client-default: '2024-06-01'
          x-ms-parameter-location: client
        x-ms-client-default: '2024-06-01'
        x-ms-parameter-location: client
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelList'
        default:
          description: An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /files:
    get:
      tags:
      - 'Files:'
      summary: "Gets a list of all files owned by the Azure OpenAI resource.\r\nThese\
        \ include user uploaded content like files with purpose \"fine-tune\" for\
        \ training or validation of fine-tunes models\r\nas well as files that are\
        \ generated by the service such as \"fine-tune-results\" which contains various\
        \ metrics for the corresponding fine-tune job."
      operationId: Files_List
      parameters:
      - name: purpose
        in: query
        description: Only return files with the given purpose.
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - fine-tune
          - fine-tune-results
          x-ms-enum:
            name: Purpose
            modelAsString: true
            values:
            - value: fine-tune
              description: This file contains training data for a fine tune job.
            - value: fine-tune-results
              description: This file contains the results of a fine tune job.
        x-ms-enum:
          name: Purpose
          modelAsString: true
          values:
          - value: fine-tune
            description: This file contains training data for a fine tune job.
          - value: fine-tune-results
            description: This file contains the results of a fine tune job.
      - name: api-version
        in: query
        description: The requested API version.
        required: true
        style: form
        explode: true
        schema:
          type: string
          x-ms-client-default: '2024-06-01'
          x-ms-parameter-location: client
        x-ms-client-default: '2024-06-01'
        x-ms-parameter-location: client
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileList'
        default:
          description: An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
      - 'Files:'
      summary: Creates a new file entity by uploading data from a local machine. Uploaded
        files can, for example, be used for training or evaluating fine-tuned models.
      operationId: Files_Upload
      parameters:
      - name: api-version
        in: query
        description: The requested API version.
        required: true
        style: form
        explode: true
        schema:
          type: string
          x-ms-client-default: '2024-06-01'
          x-ms-parameter-location: client
        x-ms-client-default: '2024-06-01'
        x-ms-parameter-location: client
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - file
              - purpose
              type: object
              properties:
                purpose:
                  type: string
                  description: The intended purpose of the uploaded documents. Use
                    "fine-tune" for fine-tuning. This allows us to validate the format
                    of the uploaded file.
                  enum:
                  - fine-tune
                  - fine-tune-results
                  x-ms-enum:
                    name: Purpose
                    modelAsString: true
                    values:
                    - value: fine-tune
                      description: This file contains training data for a fine tune
                        job.
                    - value: fine-tune-results
                      description: This file contains the results of a fine tune job.
                file:
                  type: string
                  description: Gets or sets the file to upload into Azure OpenAI.
                  format: binary
        required: true
      responses:
        '201':
          description: The file has been successfully created.
          headers:
            Location:
              description: The location of the newly created item.
              style: simple
              explode: false
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        default:
          description: An error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Capabilities:
      title: Capabilities
      required:
      - chat_completion
      - completion
      - embeddings
      - fine_tune
      - inference
      type: object
      properties:
        fine_tune:
          type: boolean
          description: A value indicating whether a model can be used for fine tuning.
        inference:
          type: boolean
          description: A value indicating whether a model can be deployed.
        completion:
          type: boolean
          description: A value indicating whether a model supports completion.
        chat_completion:
          type: boolean
          description: A value indicating whether a model supports chat completion.
        embeddings:
          type: boolean
          description: A value indicating whether a model supports embeddings.
      description: The capabilities of a base or fine tune model.
    Deprecation:
      title: Deprecation
      required:
      - inference
      type: object
      properties:
        fine_tune:
          type: integer
          description: The end date of fine tune support of this model. Will be `null`
            for fine tune models.
          format: unixtime
        inference:
          type: integer
          description: The end date of inference support of this model.
          format: unixtime
      description: "Defines the dates of deprecation for the different use cases of\
        \ a model.\r\nUsually base models support 1 year of fine tuning after creation.\
        \ Inference is typically supported 2 years after creation of base or\r\nfine\
        \ tuned models. The exact dates are specified in the properties."
    Error:
      title: Error
      required:
      - code
      - message
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          minLength: 1
          type: string
          description: The message of this error.
        target:
          type: string
          description: The location where the error happened if available.
        details:
          type: array
          description: The error details if available.
      description: "Error content as defined in the Microsoft REST guidelines\r\n\
        (https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses)."
    ErrorCode:
      title: ErrorCode
      type: string
      description: "Error codes as defined in the Microsoft REST guidelines\r\n(https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses)."
      enum:
      - conflict
      - invalidPayload
      - forbidden
      - notFound
      - unexpectedEntityState
      - itemDoesAlreadyExist
      - serviceUnavailable
      - internalFailure
      - quotaExceeded
      - jsonlValidationFailed
      - fileImportFailed
      - tooManyRequests
      - unauthorized
      - contentFilter
      x-ms-enum:
        name: ErrorCode
        modelAsString: true
        values:
        - value: conflict
          description: The requested operation conflicts with the current resource
            state.
        - value: invalidPayload
          description: The request data is invalid for this operation.
        - value: forbidden
          description: The operation is forbidden for the current user/api key.
        - value: notFound
          description: The resource is not found.
        - value: unexpectedEntityState
          description: The operation cannot be executed in the current resource's
            state.
        - value: itemDoesAlreadyExist
          description: The item does already exist.
        - value: serviceUnavailable
          description: The service is currently not available.
        - value: internalFailure
          description: Internal error. Please retry.
        - value: quotaExceeded
          description: Quota exceeded.
        - value: jsonlValidationFailed
          description: Validation of jsonl data failed.
        - value: fileImportFailed
          description: Import of file failed.
        - value: tooManyRequests
          description: Too many requests. Please retry later.
        - value: unauthorized
          description: The current user/api key is not authorized for the operation.
        - value: contentFilter
          description: Image generation failed as a result of our safety system.
    ErrorResponse:
      title: ErrorResponse
      required:
      - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/Error'
      description: "Error response as defined in the Microsoft REST guidelines\r\n\
        (https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses)."
    File:
      title: File
      required:
      - filename
      - purpose
      type: object
      properties:
        object:
          $ref: '#/components/schemas/TypeDiscriminator'
        created_at:
          type: integer
          description: A timestamp when this job or item was created (in unix epochs).
          format: unixtime
          readOnly: true
        id:
          type: string
          description: The identity of this item.
          readOnly: true
        status:
          $ref: '#/components/schemas/FileState'
        bytes:
          type: integer
          description: "The size of this file when available (can be null). File sizes\
            \ larger than 2^53-1 are not supported to ensure compatibility\r\nwith\
            \ JavaScript integers."
          format: int64
          readOnly: true
        purpose:
          $ref: '#/components/schemas/Purpose'
        filename:
          minLength: 1
          type: string
          description: The name of the file.
        status_details:
          type: string
          description: The error message with details in case processing of this file
            failed.
          readOnly: true
      description: A file is a document usable for training and validation. It can
        also be a service generated document with result details.
    FileList:
      title: FileList
      type: object
      properties:
        object:
          $ref: '#/components/schemas/TypeDiscriminator'
        data:
          type: array
          description: The list of items.
          items:
            $ref: '#/components/schemas/File'
      description: Represents a list of files.
    FileState:
      title: FileState
      type: string
      description: The state of a file.
      enum:
      - uploaded
      - pending
      - running
      - processed
      - error
      - deleting
      - deleted
      x-ms-enum:
        name: FileState
        modelAsString: true
        values:
        - value: uploaded
          description: The file has been uploaded but it's not yet processed. This
            state is not returned by Azure OpenAI and exposed only for compatibility.
            It can be categorized as an inactive state.
        - value: pending
          description: The operation was created and is not queued to be processed
            in the future. It can be categorized as an inactive state.
        - value: running
          description: The operation has started to be processed. It can be categorized
            as an active state.
        - value: processed
          description: The operation has successfully be processed and is ready for
            consumption. It can be categorized as a terminal state.
        - value: error
          description: The operation has completed processing with a failure and cannot
            be further consumed. It can be categorized as a terminal state.
        - value: deleting
          description: The entity is ni the process to be deleted. This state is not
            returned by Azure OpenAI and exposed only for compatibility. It can be
            categorized as an active state.
        - value: deleted
          description: The entity has been deleted but may still be referenced by
            other entities predating the deletion. It can be categorized as a terminal
            state.
    FineTuningState:
      title: FineTuningState
      type: string
      description: The state of a finetunes object or fine tuning job.
      enum:
      - created
      - pending
      - running
      - succeeded
      - cancelled
      - failed
      x-ms-enum:
        name: FineTuningState
        modelAsString: true
        values:
        - value: created
          description: The operation was created. This state is not returned by Azure
            OpenAI and exposed only for compatibility. It can be categorized as an
            inactive state.
        - value: pending
          description: The operation is not yet queued to be processed in the future.
            It can be categorized as an inactive state.
        - value: running
          description: The operation has started to be processed. It can be categorized
            as an active state.
        - value: succeeded
          description: The operation has successfully be processed and is ready for
            consumption. It can be categorized as a terminal state.
        - value: cancelled
          description: The operation has been cancelled and is incomplete. It can
            be categorized as a terminal state.
        - value: failed
          description: The operation has completed processing with a failure and cannot
            be further consumed. It can be categorized as a terminal state.
    LifeCycleStatus:
      title: LifeCycleStatus
      type: string
      description: "The life cycle status of a model.\r\nNote: A model can be promoted\
        \ from \"preview\" to \"generally-available\", but never from \"generally-available\"\
        \ to \"preview\"."
      enum:
      - preview
      - generally-available
      x-ms-enum:
        name: LifeCycleStatus
        modelAsString: true
        values:
        - value: preview
          description: Model is in preview and covered by the service preview terms.
        - value: generally-available
          description: Model is generally available.
    Model:
      title: Model
      required:
      - capabilities
      - deprecation
      - lifecycle_status
      type: object
      properties:
        object:
          $ref: '#/components/schemas/TypeDiscriminator'
        created_at:
          type: integer
          description: A timestamp when this job or item was created (in unix epochs).
          format: unixtime
          readOnly: true
        id:
          type: string
          description: The identity of this item.
          readOnly: true
        status:
          $ref: '#/components/schemas/FineTuningState'
        model:
          type: string
          description: The base model identity (model-id) if this is a fine tune model;
            otherwise `null`.
        fine_tune:
          type: string
          description: The fine tune job identity (fine-tune-id) if this is a fine
            tune model; otherwise `null`.
        capabilities:
          $ref: '#/components/schemas/Capabilities'
        lifecycle_status:
          $ref: '#/components/schemas/LifeCycleStatus'
        deprecation:
          $ref: '#/components/schemas/Deprecation'
      description: A model is either a base model or the result of a successful fine
        tune job.
    ModelList:
      title: ModelList
      type: object
      properties:
        object:
          $ref: '#/components/schemas/TypeDiscriminator'
        data:
          type: array
          description: The list of items.
          items:
            $ref: '#/components/schemas/Model'
      description: Represents a list of models.
    Purpose:
      title: Purpose
      type: string
      description: The intended purpose of the uploaded documents. Use "fine-tune"
        for fine-tuning. This allows us to validate the format of the uploaded file.
      enum:
      - fine-tune
      - fine-tune-results
      x-ms-enum:
        name: Purpose
        modelAsString: true
        values:
        - value: fine-tune
          description: This file contains training data for a fine tune job.
        - value: fine-tune-results
          description: This file contains the results of a fine tune job.
    TypeDiscriminator:
      title: TypeDiscriminator
      type: string
      description: Defines the type of an object.
      enum:
      - list
      - fine_tuning.job
      - file
      - fine_tuning.job.event
      - fine_tuning.job.checkpoint
      - model
      x-ms-enum:
        name: TypeDiscriminator
        modelAsString: true
        values:
        - value: list
          description: This object represents a list of other objects.
        - value: fine_tuning.job
          description: This object represents a fine tune job.
        - value: file
          description: This object represents a file.
        - value: fine_tuning.job.event
          description: This object represents an event of a fine tuning job.
        - value: fine_tuning.job.checkpoint
          description: This object represents a checkpoint of a fine tuning job.
        - value: model
          description: This object represents a model (can be a base model or fine
            tune job result).
